### ISSUE TITLE
Map of Entire Earth on Screen

### ISSUE THREAD

**Issue by CarsonPiehl** [CarsonPiehl/EONET-Earth-Visualizer#6]
Have the entire Earth on the screen on the map. The map should be full screen.

**Comment by thePlebDev** [comment]
if this is still open I can do this with leaflet js. if that is acceptable

**Comment by CarsonPiehl** [comment]
@thePlebDev Apologies, this is a school project, so as much as I would love your help, I don't think it would fly with the teacher. I'll make sure to set this to private so we don't gaslight people, lol.
